server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/blog?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: zkak
    password: zkak1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #테이블이 있어도 실행할 때 마다 새로 만듬. update - 기존 데이터에 추가해서 작성
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false #jpa가 사용하는 기본 넘버링 전략을 따라가지 않음 ->@GenetatedValue 에서 전략설정.
    show-sql: true #hibernate가 DB에 날리는 모든 쿼리(DDL,DML) 를 보여줌
    properties:
      hibernate.format_sql: true # 보여지는 쿼리를 보기좋게 포맷팅

  jackson:
    serialization:
      fail-on-empty-beans: false

